Porting //eve/staging/2018-IRPA->//eve/development/MAINLINE at head (1421292) - using branchspec //eve/staging/2018-IRPA->//eve/development/MAINLINE
========================================

Change 1421190 by freyr@eve_branches_staging_2018-IRPA_freyr-pc on 2018/11/14 13:27:18

AttributeError: 'NoneType' object has no attribute 'shipID'
https://jira.ccpgames.com/browse/TQ-130820

if we can't find a client session for the character to attribute the npc kill there is not much we can do.  Adding handling where we dont have the client session info and do nothing in that case.

========================================

Change 1421192 by dmaxson@dmaxson_DMAXSON-WS_1633 on 2018/11/14 13:29:42

Don't send duplicate skill alerts for characters

Review: http://codecollaborator/ui#review:id=16960

========================================

Change 1421196 by filipp@eve_branches_staging_2018-IRPA_filipp-pc on 2018/11/14 13:32:06

Particles show up on the ship as it is landing on Gallente Gate gsmg
https://jira.ccpgames.com/browse/TQ-130839

========================================

Change 1421236 by hjaltil@eve_branches_staging_2018-IRPA_hjaltil-pc on 2018/11/14 14:23:23

Activity Tracker: Delivering a corporation industry job increments the Industry nodes of the player that delivered the job instead of the one that started it https://jira.ccpgames.com/browse/TQ-130836

* All industry jobs now count towards the installers Activity Tracker, not the player who delivered the job.

========================================

Change 1421285 by freyr@eve_branches_staging_2018-IRPA_freyr-pc on 2018/11/14 14:52:54

UserError eve.server.script.mgt.inv.inventory in GetItemByID errorUser error, msg=FakeItemNotFound, dict=None
https://jira.ccpgames.com/browse/TQ-130818

fixing a unitest I broke in Change 1421069 by freyr@eve_branches_staging_2018-IRPA_freyr-pc on 2018/11/14 10:58:40

========================================

Change 1421292 by dmaxson@dmaxson_DMAXSON-WS_1633 on 2018/11/14 14:58:00

Remove dates from notification IDs

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1421335]